[package]
name = "ammber-charts"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { workspace = true }
leptos-chartistry = { version = "0.2.1" }

[[bin]]
name = "demo"
path = "demo/demo.rs"
