[serve]
port = 8080
serve_base = "/liquidity-book-leptos/"

[build]
target = "index.html"
dist = "../dist/"
public_url = "/liquidity-book-leptos/"

[watch]
watch = ["../components/", "../features/", "../core/"]
