[package]
name = "secret-batch-query"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
tracing = "0.1.41"
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.1.11" }
