[package]
name = "secret-batch-query"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
base64 = { workspace = true }

cosmwasm-std = { workspace = true }

tracing = { workspace = true }
